### ISSUE TITLE
answer links template fails silently

### ISSUE THREAD

**Issue by aaronoppenheimer** [SecondLiners/GO3#33]
https://github.com/SecondLiners/GO3/blob/33e164e2df6be40bb0066aff69a518114670e110/gig/tests.py#L278

When I run the gig tests from the command line, they pass, but my IDE notes that there's a template that fails to be rendered. This seems to be because the 'answer' page template extends go3base.html which itself includes the MOTD template, which expects there to be a logged-in user and there isn't - the user is a generic anonymous user.

**Comment by rschroll** [comment]
I'm not seeing a problem in practice.  I can hit the answer endpoint in an incognito window, and everything seems to work correctly.  It does look like the `if user` check in the base template isn't doing anything, since the AnonymousUser passes it.  I guess we should be checking the user isn't anonymous?

**Comment by aaronoppenheimer** [comment]
Yes, I think that's all there is to it.

**Comment by aaronoppenheimer** [comment]
Fixed in caldav branch
