### ISSUE TITLE
Failing timezone test

### ISSUE THREAD

**Issue by aaronoppenheimer** [SecondLiners/GO3#44]
https://github.com/SecondLiners/GO3/blob/11952ae0a1f47eda4c738d4f34c8b50b648bf433/gig/tests.py#L173

This is failing because:
- band timezone is set to New York on line 166
- gig is created for noon in band's timezone
- email is checked to see if time is properly offset for timezone - but test expects time to be shifted as if the gig date was in UTC

What's the intent? Should we be leaving the band tz in default UTC?

**Comment by rschroll** [comment]
This test was created in 30da2e1, and I wasn't quite sure what it's trying to test.  From the test name, it seems to be testing that the times are localized correctly.  But this is implicitly tested for english in `test_new_gig_email` and explicitly tested for german in `test_new_gig_localization`.  Since it was also adjusting time zones, it might also be testing that we're storing and interpreting time-zone-aware dates correctly.

Originally, both the band and the gig were in UTC, but we switched to ET to prepare the email.  This was before we set the timezone of the email from the band.  With this change, I set the band to ET, while setting the gig time in UTC, to the same result.  However, commit 6650dcf sets the test gig TZ from the band TZ, making this split impossible.  After the merge, this test fails.

So, if the purpose was to test localization of times, I think it's already covered and we could get rid of this test.  If the purpose was to check that times are correctly displayed when there's a mismatch between gig and band timezones, then we need to ensure that these two are different.

**Comment by aaronoppenheimer** [comment]
Well, no idea what happened, but no matter.

Gig and band timezones will almost always be the same. Sometimes a band might travel to another zone to play a gig at Honk!Timbuktu or something, so in that case it'd be nice to let them override the TZ for a gig so that things show up properly on calendars. So I'll update this to explicity demonstrate that a gig with one TZ shows up properly when the band has another - it's probably redundant but since timezones are a pain, more test is better.

Thanks for digging into this!

A

**Comment by aaronoppenheimer** [comment]
Hey, you already fixed it! Thanks.
